#!/bin/bash

# Setup environment variables from CDK outputs
# This script retrieves the CloudFront domain, API endpoint, and Cognito configuration
# from the deployed CDK stacks and generates a .env file

set -e

# Configuration
ENVIRONMENT="${1:-dev}"
REGION="eu-central-1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=========================================="
echo "Environment Setup Script"
echo "=========================================="
echo "Environment: $ENVIRONMENT"
echo "Region: $REGION"
echo ""

# Validate environment
if [[ "$ENVIRONMENT" != "dev" ]]; then
    echo "Error: This project is dev-only. Environment must be 'dev'"
    exit 1
fi

# Get stack names
FRONTEND_STACK="DataCollectionFrontend-$ENVIRONMENT"
API_STACK="DataCollectionAPI-$ENVIRONMENT"
COGNITO_STACK="DataCollectionCognito-$ENVIRONMENT"

echo "Retrieving outputs from CDK stacks..."
echo ""

# Get CloudFront domain
echo "Getting CloudFront domain..."
CLOUDFRONT_DOMAIN=$(aws cloudformation describe-stacks \
    --stack-name "$FRONTEND_STACK" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDomainName'].OutputValue" \
    --output text 2>/dev/null || echo "")

if [[ -z "$CLOUDFRONT_DOMAIN" ]]; then
    echo "Error: Could not retrieve CloudFront domain"
    echo "Make sure the frontend stack has been deployed: cdk deploy DataCollectionFrontend-$ENVIRONMENT"
    exit 1
fi

echo "  CloudFront Domain: $CLOUDFRONT_DOMAIN"

# Get API endpoint
echo "Getting API endpoint..."
API_ENDPOINT=$(aws cloudformation describe-stacks \
    --stack-name "$API_STACK" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='APIEndpoint'].OutputValue" \
    --output text 2>/dev/null || echo "")

if [[ -z "$API_ENDPOINT" ]]; then
    echo "Error: Could not retrieve API endpoint"
    echo "Make sure the API stack has been deployed: cdk deploy DataCollectionAPI-$ENVIRONMENT"
    exit 1
fi

echo "  API Endpoint: $API_ENDPOINT"

# Get Cognito configuration
echo "Getting Cognito configuration..."

# Get Cognito User Pool ID
COGNITO_USER_POOL_ID=$(aws cloudformation describe-stacks \
    --stack-name "$COGNITO_STACK" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" \
    --output text 2>/dev/null || echo "")

if [[ -z "$COGNITO_USER_POOL_ID" ]]; then
    echo "Error: Could not retrieve Cognito User Pool ID"
    echo "Make sure the Cognito stack has been deployed: cdk deploy DataCollectionCognito-$ENVIRONMENT"
    exit 1
fi

echo "  Cognito User Pool ID: $COGNITO_USER_POOL_ID"

# Get Cognito Hosted UI domain
COGNITO_DOMAIN=$(aws cloudformation describe-stacks \
    --stack-name "$COGNITO_STACK" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='HostedUiDomain'].OutputValue" \
    --output text 2>/dev/null || echo "")

if [[ -z "$COGNITO_DOMAIN" ]]; then
    echo "Error: Could not retrieve Cognito Hosted UI domain"
    exit 1
fi

echo "  Cognito Hosted UI Domain: $COGNITO_DOMAIN"

# Get Cognito client ID
COGNITO_CLIENT_ID=$(aws cloudformation describe-stacks \
    --stack-name "$COGNITO_STACK" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" \
    --output text 2>/dev/null || echo "")

if [[ -z "$COGNITO_CLIENT_ID" ]]; then
    echo "Error: Could not retrieve Cognito client ID"
    exit 1
fi

echo "  Cognito Client ID: $COGNITO_CLIENT_ID"

# Create .env file
echo ""
echo "Creating .env file..."

ENV_FILE="$SCRIPT_DIR/.env"
cat > "$ENV_FILE" << EOF
# Frontend Environment Configuration
# Auto-generated by setup-env.sh on $(date)
# Environment: $ENVIRONMENT

# API Gateway endpoint URL
API_ENDPOINT=$API_ENDPOINT

# Cognito configuration
COGNITO_DOMAIN=$COGNITO_DOMAIN
COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID
COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID
COGNITO_REDIRECT_URI=https://$CLOUDFRONT_DOMAIN

# CloudFront domain for CORS
CLOUDFRONT_DOMAIN=$CLOUDFRONT_DOMAIN

# Environment name
ENVIRONMENT=$ENVIRONMENT

EOF

echo ".env file created at: $ENV_FILE"
echo ""

# Display the configuration
echo "=========================================="
echo "Configuration Summary"
echo "=========================================="
echo "API Endpoint: $API_ENDPOINT"
echo "Cognito Hosted UI Domain: $COGNITO_DOMAIN"
echo "Cognito User Pool ID: $COGNITO_USER_POOL_ID"
echo "Cognito Client ID: $COGNITO_CLIENT_ID"
echo "CloudFront Domain: $CLOUDFRONT_DOMAIN"
echo "Environment: $ENVIRONMENT"
echo ""

# Verify the .env file
echo "Verifying .env file..."
if [ -f "$ENV_FILE" ]; then
    echo "✓ .env file created successfully"
    echo ""
    echo "Next steps:"
    echo "  1. Review the .env file: cat $ENV_FILE"
    echo "  2. Build the frontend: bash build.sh"
    echo "  3. Deploy to S3: bash deploy.sh $ENVIRONMENT"
    echo ""
else
    echo "✗ Failed to create .env file"
    exit 1
fi
